### ISSUE TITLE
Compiled .pyd files need update for ComfyUI DifferentialDiffusion V3 API

### ISSUE THREAD

**Issue by janoschsimon** [Ltamann/ComfyUI-TBG-ETUR#50]
Hey, just wanted to report that TBG workflows completely break when updating ComfyUI to v0.3.62 or newer. Getting AttributeError: 'DifferentialDiffusion' object has no attribute 'apply' when the TBG Enhanced Refiner tries to run.
I spent hours debugging this and found that ComfyUI changed their DifferentialDiffusion API on October 1st 2025 (commit e0210ce0) to V3 schema. The compiled .pyd files in py/nodes/UpscalerRefiner/ are built against the old API and don't work with the new one.
I tried downgrading TBG to versions 1.08v3, 1.08v2, 1.08v1, 1.07v1, and even 1.06v2 but they all have the same error because they use the same compiled files. I also tried different ComfyUI versions including v0.3.62 and commit 3af18814 (right before the DifferentialDiffusion change) but nothing worked.
The only solution I found was to downgrade ComfyUI to commit b60dc316 (September 27, 2025) which is v0.3.60 - before they changed the API. That works perfectly but it means I'm stuck on an old ComfyUI version and can't use any new features.
Would be great if you could recompile the .pyd files for the new ComfyUI API. But honestly, this whole situation shows that using compiled binaries is really problematic long-term. Every time ComfyUI updates their API, all your users are stuck until you recompile. It would be much better to release the code as regular Python files so users can stay current with ComfyUI or even patch things themselves if needed. 
Thanks!

janosch

**Comment by mostafaelgebaly** [comment]
I did some research also it's stuck at the old denoise_sigmas.
logs: 
 File "C:\Users\user\DOCUME~1\ComfyUI\CUSTOM~1\COC331~1\py\nodes\UPSCAL~1\TBG_Refiner.py", line 132, in fn
  File "C:\Users\user\DOCUME~1\ComfyUI\CUSTOM~1\COC331~1\py\nodes\UPSCAL~1\TBG_Refiner.py", line 703, in refine
TypeError: denoise_sigmas() takes 3 positional arguments but 5 were given

2025-10-05T14:29:34.815523 - Prompt executed in 0.43 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by Ltamann** [comment]
I’m using ComfyUI version 0.3.60. I’ll check, but they’re updating all nodes to the new Schema V3, which could potentially cause some issues. Maybe that’s what’s happening here.

**Comment by Ltamann** [comment]
it's only a name conflict - ComfyUI now have a function with the same name, and this is a priority. I will rename my function and upload the changes.

**Comment by Ltamann** [comment]
Try it out should work now

**Comment by Ltamann** [comment]
Did not found any issue with DifferentialDiffusion only with denoise_sigmas() - becouse of the naming conflict. Can you point me in the direction how to repoduce the error.

**Comment by Ltamann** [comment]
Found the DifferentialDiffusion change — they renamed the apply function to execute. Fix uploaded.
